import type { Metadata } from "next";
import "../globals.css";

import { Montserrat } from "next/font/google";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Copywrite from "@/components/Copywrite";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TheNetSense",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar />
        {children}
        <Footer />
        <Copywrite />
      </body>
    </html>
  );
}
